kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      id: sqlpv
