apiVersion: v1
kind: Service
metadata:
  name: mssql-svc
  labels:
    app: mssql
spec:
  type: NodePort
  ports:
    - name: mssql
      port: 1443
      protocol: TCP
      targetPort: 1433  
  selector:
    app: mssql